import Navbar from "./components/navbar"
import Footer from "./components/footer.js"
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
